#if _NET_4 && _M_AMD64
//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
// Assembly                 : mscorlib
// Runtime Version          : v4.0.30319
// Assembly Version         : 4.0.0.0
// Processor Architecture   : AMD64
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------


using Urasandesu.Prig.Framework;

[assembly: Indirectable(System.Prig.PDateTimeBase.TokenOfNowGet)]

namespace System.Prig
{
    public abstract class PDateTimeBase
    {
        internal const int TokenOfNowGet = 0x06000523;
    }
}
#endif
